### ISSUE TITLE
Expose total_pages in meta

### ISSUE THREAD

**Issue by jsteiner** [nsweeting/query#2]
It might be handy to expose `total_pages` (i.e. something like: `round(Float.ceil(total / page_total))`) in `meta`.

This would be useful for rendering a "Last Page" link.

**Comment by nsweeting** [comment]
Thanks for your feedback @jsteiner! Implemented in v 0.1.2

**Comment by nsweeting** [comment]
and fixed in v 0.1.3.... its been a long day :)
